name: 'R2 download artifact'
description: 'Downloads an artifact from R2.'

inputs:
  file-path:
    description: 'Path to the file is.'
    required: true
  r2-storage-bucket:
    description: 'Storage bucket to use to store the artifacts'
    required: true
  r2-api-id:
    description: 'Account ID for R2'
    required: true
  r2-auth-token-id:
    description: 'ID of the authentication token for R2'
    required: true
  r2-auth-token:
    description: 'Authentication token for R2'
    required: true
  r2-region:
    description: 'Region for the R2 account'
    required: true
  r2-path:
    description: 'Path within R2 where to put the file.'
    required: true
  put-path:
    description: 'File path where to put the files.'
    required: true

outputs:
  cache-hit:
    description: 'Returns if the cache was hit or not.'
    value: ${{ steps.cache-status.outputs.status }}

runs:
  using: composite
  steps:
    - name: 'Install dependencies'
      shell: bash
      run: |
        apt-get update
        apt-get install -y s3cmd

    - name: 'Get the file'
      shell: bash
      id: s3get
      continue-on-error: true
      run: s3cmd --access_key=${{ inputs.r2-auth-token-id }} --secret_key=${{ inputs.r2-auth-token }} --region=${{ inputs.r2-region }} --host=https://${{ inputs.r2-api-id }}.r2.cloudflarestorage.com get s3://${{ inputs.r2-storage-bucket }}/github/${{ inputs.file-path }}/files.tar.zstd .

    - name: 'Decompress file to path'
      shell: bash
      id: decomp
      continue-on-error: true
      run: tar -xf files.tar.zstd -C ${{ inputs.put-path }}

    - name: 'Return cache success'
      shell: bash
      id: cache-status
      run: |
        if [ "${{ steps.s3get.conclusion }}" != "success" ] || [ "${{ steps.decomp.conclusion }}" != "success" ]; then
          echo "status=false" >> $GITHUB_ENV
        else
          echo "status=true" >> $GITHUB_ENV
        fi
