name: 'Download and cache Unity Runtime'
description: 'Downloads the Unity runtime with heavy caching.'

inputs:
  version:
    description: 'The version of Unity to download'
    required: false
    default: '2019.4.19f1'
  build-target:
    description: 'Build target for Unity'
    required: false
    default: 'StandaloneWindows64'
  modules:
    description: 'Modules to install, use comma separated list'
    required: false
    default: |
      windows-server
      universal-windows-platform
  r2-storage-bucket:
    description: 'Storage bucket to use to store the artifacts'
    required: true
  r2-api-id:
    description: 'Account ID for R2'
    required: true
  r2-auth-token-id:
    description: 'ID of the authentication token for R2'
    required: true
  r2-auth-token:
    description: 'Authentication token for R2'
    required: true
  r2-region:
    description: 'Region for the R2 account'
    required: true

runs:
  using: composite
  steps:
    - name: 'setup Unity'
      uses: buildalon/unity-setup@v2
      with:
        unity-version: ${{ inputs.version }}
        build-targets: ${{ inputs.build-target }}
        modules: ${{ inputs.modules }}
        cache-installation: true
