name: 'Docker build push'
description: 'Builds a Docker container and pushes it to the specified registry.'

inputs:
  docker-version:
    description: 'Docker version to install.'
    default: 'latest'
    required: false
  docker-registry:
    description: 'Registry which Docker will push to.'
    default: 'ghcr.io'
    required: false
  docker-token:
    description: 'Docker auth token for the registry.'
    required: true
  dockerfile-path:
    description: 'Path to the Dockerfile file.'
    default: '${{ github.workspace }}/Dockerfile'
    required: false
  docker-context-path:
    description: 'Context to pass to the Docker daemon for the build.'
    default: '.'
    required: false
  docker-platforms:
    description: 'List of platforms to build the image for.'
    default: 'linux/amd64'
    required: false

runs:
  using: composite

  steps:
    - name: 'Set QEMU'
      uses: docker/setup-qemu-action@v3

    - name: 'Setup Buildx'
      uses: docker/setup-buildx-action@v3
      with:
        version: ${{ inputs.docker-version }}

    - name: 'Extract metadata for build'
      id: metadata
      uses: docker/metadata-action@v5

    - name: 'Login to registry'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.docker-token }}

    - name: 'Build and push the image'
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.docker-context-path }}
        file: ${{ inputs.dockerfile-path }}
        push: 'true'
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        platforms: ${{ inputs.docker-platforms }}
