name: '.NET Push NuGet'
description: 'Pushes nugets the registry'

inputs:
  dotnet-nuget-out-path:
    description: 'Path under which Nugets will be put after the build.'
    default: '${{ github.workspace }}/nupkgs'
    required: false
  dotnet-nuget-registry-url:
    description: 'Publishing URL of the NuGet registry.'
    default: 'https://api.nuget.org/v3/index.json'
    required: false
  dotnet-nuget-auth-token:
    description: 'Authentication token for the NuGet registry.'
    required: true

runs:
  using: composite

  steps:
    - name: 'Publish package to registry'
      shell: bash
      run: dotnet nuget push ${{ inputs.dotnet-nuget-out-path }}/*.nupkg -k ${{ inputs.dotnet-nuget-auth-token }} -s ${{ inputs.dotnet-nuget-registry-url }}
