name: Build and push Docker image to registry

on:
  workflow_call:
    inputs:
      image_name:
        description: 'The name of the Docker image you want to build and push.'
        required: true
        type: string
      image_tag:
        description: 'The tag you want applied to the Docker iamge.'
        required: false
        # Good enough for now, but we will need to accommodate for better tagging later
        # The 'latest' tag is generally nonstandard.
        default: 'latest'
        type: string
      context:
        description: 'The build context passed to Docker. Only change this if you really need to.'
        required: false
        default: '.'
        type: string
      dockerfile:
        description: 'The name and path of the Dockerfile. Only change this if you really need to.'
        required: false
        default: 'Dockerfile'
        type: string
      docker_registry:
        description: 'Registry used by Docker. Defaults to ghcr.io.'
        required: false
        default: 'ghcr.io'
        type: string
      secrets:
        LOGIN_TOKEN:
          description: 'Authentication token'
          required: true

job:
  build-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.LOGIN_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
