name: Run tests using .NET

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: 'The version of .NET to use. Defaults to 9.0.x'
        required: false
        default: '9.0.x'
        type: string

jobs:
  text-dotnet:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Run tests
        run: dotnet test
